### ISSUE TITLE
mi.h wrong reference to SERCOM3

### ISSUE THREAD

**Issue by Sonnengruesser** [KONNEKTING/KonnektingFirmware#1]
in files mi.h, in section #ifdef useSerial3 (approx line 75), SERCOM1_Handler should be used instead of SERCOM3_Handler

**Comment by Adminius** [comment]
@Sonnengruesser pls make a pull request for it ;)

**Comment by Sonnengruesser** [comment]
das nenn ich mal "learning by doing" :)
